export const SET_LOADING_PROJECTS = "SET_LOADING_PROJECTS";
export const GET_PROJECTS = "GET_PROJECTS";
export const SET_PROJECT = "SET_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const SET_LOADING_TASKS = "SET_LOADING_TASKS";
export const GET_TASKS = "GET_TASKS";
export const ADD_TASK = "ADD_TASK";
export const ARCHIVE_TASK = "ARCHIVE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const SET_TASK = "SET_TASK";
export const DELETE_TASK = "DELETE_TASK";

export const SET_USER = "SET_USER";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
